import { Injectable } from '@nestjs/common';
import {
  PresenceRepository,
  UserRepository,
  UserStatusRecordRepository,
} from 'src/common/database/repositories';
import { RegisterDto, LoginDto } from './dto/auth.dto';
import { JwtHelper, verifyHash } from '../../common/Global/security';
import { Prisma } from '@prisma/client';
import { ApiResponse } from 'src/common/shared/types';
import { RESPONSE_MESSAGES } from 'src/common/shared/response-messages';
import { success, fail } from 'src/common/utils/response.util';
import { Response } from 'express';

@Injectable()
export class AuthService {
  constructor(
    private readonly userRepository: UserRepository,
    private readonly jwtHelper: JwtHelper,
    private readonly userStatusRecordRepository: UserStatusRecordRepository,
    private readonly presenceRepository: PresenceRepository,
  ) {}

  async register(
    registerDto: RegisterDto,
    res: Response,
  ): Promise<ApiResponse> {
    // Check if user already exists
    const existingUser = await this.userRepository.findByEmail(
      registerDto.email,
    );
    if (existingUser) {
      return {
        status: 'error',
        code: 'USER_EMAIL_EXISTS', // الكود الجديد اللي هنتعامل معاه في الفرونت
        message: 'A user with this email already exists',
        timestamp: new Date().toISOString(),
      };
    }

    // Check if username is taken
    const existingUsername = await this.userRepository.findByUsername(
      registerDto.username,
    );
    if (existingUsername) {
      return {
        status: 'error',
        code: 'USERNAME_TAKEN',
        message: 'Username is already taken',
        timestamp: new Date().toISOString(),
      };
    }

    // Create user (password will be hashed by middleware, id will be generated by middleware)
    const user = await this.userRepository.create({
      ...registerDto,
    } as Omit<Prisma.UserUncheckedCreateInput, 'id'>);
    await this.userStatusRecordRepository.createStatusRecord({
      userId: user.id,
    });
    await this.presenceRepository.createPresence(user.id);
    // Generate JWT tokens
    const accessToken = this.jwtHelper.generateToken({
      sub: user.id.toString(),
      type: 'access',
    });
    const refreshToken = this.jwtHelper.generateToken({
      sub: user.id.toString(),
      type: 'refresh',
    });
    res.cookie('Authorization', accessToken, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production' ? true : false,
      sameSite: 'lax',
      maxAge: 7 * 24 * 60 * 60 * 1000,
    });
    res.cookie('refreshToken', refreshToken, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production' ? true : false,
      sameSite: 'lax',
      maxAge: 30 * 24 * 60 * 60 * 1000,
    });

    return success(RESPONSE_MESSAGES.AUTH.USER_CREATED);
  }

  async login(loginDto: LoginDto, res: Response): Promise<ApiResponse> {
    // Find user by email
    const user = await this.userRepository.findByEmail(loginDto.email);
    if (!user) {
      return fail(RESPONSE_MESSAGES.AUTH.INVALID_CREDENTIALS);
    }

    // Verify password (you'll need to implement password verification)
    const isPasswordValid = await verifyHash(loginDto.password, user.password);
    if (!isPasswordValid) {
      return fail(RESPONSE_MESSAGES.AUTH.INVALID_CREDENTIALS);
    }
    // Generate JWT tokens
    const accessToken = this.jwtHelper.generateToken({
      sub: user.id.toString(),
      type: 'access',
    });
    const refreshToken = this.jwtHelper.generateToken({
      sub: user.id.toString(),
      type: 'refresh',
    });
    res.cookie('Authorization', accessToken, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production' ? true : false,
      sameSite: 'lax',
      maxAge: 7 * 24 * 60 * 60 * 1000,
    });
    res.cookie('refreshToken', refreshToken, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production' ? true : false,
      sameSite: 'lax',
      maxAge: 30 * 24 * 60 * 60 * 1000,
    });

    return success(RESPONSE_MESSAGES.AUTH.LOGIN_SUCCESS);
  }
}
